[0m16:14:11.323458 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1048fd3a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106610a40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1066106e0>]}


============================== 16:14:11.325691 | c66486ee-1276-46b9-8071-11995f0c428b ==============================
[0m16:14:11.325691 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:14:11.325939 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/tomvandorpe/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:16:15.816943 [debug] [MainThread]: Starter project path: /Users/tomvandorpe/Documents/dbt_core_postgres/.venv/lib/python3.12/site-packages/dbt/include/starter_project
[0m16:16:15.828810 [info ] [MainThread]: 
Your new dbt project "dbt_fundamentals_initiative" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:16:15.829381 [info ] [MainThread]: Setting up your profile.
[0m16:20:15.232510 [info ] [MainThread]: Profile dbt_fundamentals_initiative written to /Users/tomvandorpe/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:20:15.237129 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 363.95447, "process_in_blocks": "0", "process_kernel_time": 0.137967, "process_mem_max_rss": "96141312", "process_out_blocks": "0", "process_user_time": 0.59947}
[0m16:20:15.237745 [debug] [MainThread]: Command `dbt init` succeeded at 16:20:15.237613 after 363.96 seconds
[0m16:20:15.238172 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1066d61e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10663d250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106610890>]}
[0m16:20:15.238588 [debug] [MainThread]: Flushing usage events
[0m16:20:15.871865 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:20:30.382417 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108628e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b08b30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b08830>]}


============================== 16:20:30.384554 | b80c2418-a6b4-4028-91e3-9e5f2a7cf8f4 ==============================
[0m16:20:30.384554 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:20:30.384805 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/tomvandorpe/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m16:20:30.391509 [info ] [MainThread]: dbt version: 1.9.2
[0m16:20:30.391683 [info ] [MainThread]: python version: 3.12.5
[0m16:20:30.391808 [info ] [MainThread]: python path: /Users/tomvandorpe/Documents/dbt_core_postgres/.venv/bin/python
[0m16:20:30.391914 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit
[0m16:20:30.394626 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.sqlite'
[0m16:20:30.395964 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.snowflake'
[0m16:20:30.396634 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.snowflake'
[0m16:20:30.422564 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.snowflake'
[0m16:20:30.423190 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.sqlite'
[0m16:20:30.423371 [info ] [MainThread]: Using profiles dir at /Users/tomvandorpe/.dbt
[0m16:20:30.423488 [info ] [MainThread]: Using profiles.yml file at /Users/tomvandorpe/.dbt/profiles.yml
[0m16:20:30.423591 [info ] [MainThread]: Using dbt_project.yml file at /Users/tomvandorpe/Documents/dbt_core_postgres/dbt_project.yml
[0m16:20:30.423700 [info ] [MainThread]: Configuration:
[0m16:20:30.423791 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m16:20:30.423885 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m16:20:30.423975 [info ] [MainThread]: Required dependencies:
[0m16:20:30.424099 [debug] [MainThread]: Executing "git --help"
[0m16:20:30.434126 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:20:30.434473 [debug] [MainThread]: STDERR: "b''"
[0m16:20:30.434587 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:20:30.434703 [info ] [MainThread]: Connection test skipped since no profile was found
[0m16:20:30.434869 [info ] [MainThread]: [31m2 checks failed:[0m
[0m16:20:30.434981 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "dbt_core_sqlite", target "dev" invalid: Runtime Error
    Could not find adapter type sqlite!

Runtime Error
  Credentials in profile "dbt_core_test", target "dev" invalid: Runtime Error
    Could not find adapter type snowflake!

Runtime Error
  Credentials in profile "dbt_core_tom", target "dev" invalid: Runtime Error
    Could not find adapter type snowflake!

Runtime Error
  Credentials in profile "test_project_tom", target "dev" invalid: Runtime Error
    Could not find adapter type snowflake!

Runtime Error
  Credentials in profile "test_sqlite_project", target "dev" invalid: Runtime Error
    Could not find adapter type sqlite!


[0m16:20:30.435098 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/tomvandorpe/Documents/dbt_core_postgres/dbt_project.yml> not found

[0m16:20:30.435941 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.09126637, "process_in_blocks": "0", "process_kernel_time": 0.085035, "process_mem_max_rss": "95420416", "process_out_blocks": "0", "process_user_time": 0.489171}
[0m16:20:30.436139 [debug] [MainThread]: Command `dbt debug` failed at 16:20:30.436100 after 0.09 seconds
[0m16:20:30.436335 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085e9490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b08a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108753620>]}
[0m16:20:30.436501 [debug] [MainThread]: Flushing usage events
[0m16:20:31.020100 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:37:59.396117 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072d5f70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108588bc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108588950>]}


============================== 16:37:59.398437 | 2158a3e9-40f0-4085-93cf-63a4a131bba2 ==============================
[0m16:37:59.398437 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:37:59.398689 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/tomvandorpe/Documents/dbt_core_postgres', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:37:59.398916 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/tomvandorpe/Documents/dbt_core_postgres/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:37:59.400092 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04176754, "process_in_blocks": "0", "process_kernel_time": 0.078697, "process_mem_max_rss": "92012544", "process_out_blocks": "0", "process_user_time": 0.459294}
[0m16:37:59.400320 [debug] [MainThread]: Command `dbt run` failed at 16:37:59.400277 after 0.04 seconds
[0m16:37:59.400465 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f386b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108588a40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10858a2d0>]}
[0m16:37:59.400596 [debug] [MainThread]: Flushing usage events
[0m16:37:59.988229 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:41:36.276211 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060cd3a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1061611c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106161160>]}


============================== 15:41:36.278435 | 1a1f11fb-07f0-40a8-b585-d7de775c7434 ==============================
[0m15:41:36.278435 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:41:36.278688 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/tomvandorpe/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --full-refresh', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:41:36.278903 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/tomvandorpe/dbt_core_initiative/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:41:36.279805 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.02969175, "process_in_blocks": "0", "process_kernel_time": 0.085115, "process_mem_max_rss": "96387072", "process_out_blocks": "0", "process_user_time": 0.494239}
[0m15:41:36.279968 [debug] [MainThread]: Command `dbt run` failed at 15:41:36.279933 after 0.03 seconds
[0m15:41:36.280097 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106c83c20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106c83e30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106c83c80>]}
[0m15:41:36.280219 [debug] [MainThread]: Flushing usage events
[0m15:41:36.684708 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:48:22.665278 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f27e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107413e30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107413bc0>]}


============================== 16:48:22.667565 | b24ff32b-aa04-4da3-ab5c-9448e5040a37 ==============================
[0m16:48:22.667565 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:48:22.667845 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/tomvandorpe/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:48:22.668084 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/tomvandorpe/dbt_core_initiative/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:48:22.669257 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.03091771, "process_in_blocks": "0", "process_kernel_time": 0.085569, "process_mem_max_rss": "95846400", "process_out_blocks": "0", "process_user_time": 0.489347}
[0m16:48:22.669446 [debug] [MainThread]: Command `dbt test` failed at 16:48:22.669408 after 0.03 seconds
[0m16:48:22.669589 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072d4d40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107413ce0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107413c20>]}
[0m16:48:22.669717 [debug] [MainThread]: Flushing usage events
[0m16:48:23.275377 [debug] [MainThread]: An error was encountered while trying to flush usage events
